# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    working_directory: ~/newton-flix

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - newton-flix-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - newton-flix-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: newton-flix-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn package

      - store_test_results:
          path: target/surefire-reports

      - store_test_results:
          path: target/failsafe-reports

      - store_artifacts:
          path: target/newton-flix-1.0.0.jar
